### ISSUE TITLE
Missing dt in sigma2 trace normalization?

### ISSUE THREAD

**Issue by yilun-wu** [fmi-basel/latent-predictive-learning#4]
Dear authors,

I believe a multiplication of `auryn_timestep` is missing from the following normalization of the trace to be consistent with Eq. 20, can you confirm?
https://github.com/fmi-basel/latent-predictive-learning/blob/dd486d092b8cea9bfa1f27f42209f9174b82e61c/spiking_simulations/LPLConnection.cpp#L485-L485

Of course, I understand the impact of this can be absorbed in $\lambda$ in Eq. 18.

**Comment by fzenke** [comment]
Looks like you are right. Thanks for flagging this!
